page_blocks: []
_array_structures:
  content-blocks:
    values:
      - label: Floating Socials
        icon: groups
        value: 
          _section-type: floating-socials
          description: To change the colors, go to data → general → social links. To change the colors, go to data → navigation → social link colors
      - label: Hero
        icon: star
        value:
          _section-type: hero
          content-block-link:
          hero-image:
          hero:
          hero-color:
          hero-font:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Textarea
        icon: article
        value:
          _section-type: textarea
          content-block-link:
          textarea_html:
          subheading_html:
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
          colors:
            background-color: 
            text-color: 
            subheading-color: 
            top-line-color: 
            left-line-color:
          fonts:
            subheading-font: 
            text-font:   
      - label: Carousel
        icon: view_carousel
        value:
          _section-type: carousel
          content-block-link:
          background_image:
          heading:
          carousel:
            textarea:
            symbols:
            ending:
          colors:
            carousel-background-color: 
            carousel-textarea-background-color: 
            carousel-border-color: 
            carousel-heading-color: 
            carousel-subheading-color: 
            carousel-text-color: 
            carousel-symbols-color:
          fonts:
            carousel-heading-font:
            carousel-subheading-font:
            carousel-text-font: 
          link:
            description:  If you would like that awesome scroll feature that happens when someone clicks on a link in the navigation, then you'll need to add a page id. The page id can be added in the below box labeled "link". Your id is a short word describing the section it is leading to. For example- about. If you don't want this section to link from the navigation, you can simply leave it out.
            link:
      - label: Fig Hover Block
        icon: emoji_nature
        value: 
          _section-type: fig-hover-block
          content-block-link:
          left:
            heading:
            textarea_html:
            background-image:
            button: 
            button-link:
          right:
            subheading:
            textarea_html:
            background-image: 
            button: 
            button-link:
          colors:
            overlay-color: 
            background-color:
            border-color: 
            heading-color: 
            hover-text-color: 
            button-background-color:
            button-text-color: 
          fonts:
            heading-font:
            subheading-font:
            textarea-font: 
      - label: Zuko Hover Block
        icon: pets
        value: 
          _section-type: zuko-hover-block
          content-block-link:
          left:
            subheading:
            textarea_html:
            background-image: 
            button:
            button-link: 
          right:
            subheading: 
            textarea_html:
            background-image:
            button: 
            button-link: 
          colors:
            overlay-color: 
            background-color:
            border-color: 
            heading-color: 
            hover-overlay-color: 
            textarea-color: 
            button-background-color:
            button-text-color: 
          fonts:
            heading-font:
            subheading-font:
            textarea-font:          
      - label: Gallery
        icon: photo_camera
        value:
          _section-type: gallery
          content-block-link:
          heading: Gallery
          left:
            top-image:  
            bottom-image:  
          middle:
            top-image:
            bottom-image: 
          right:
            top-image:
            bottom-image:
          colors:
            background-color:
            heading-color:
          fonts:
            heading-font:    
      - label: Form
        icon: email
        value:
          _section-type: form
          content-block-link:
          background_image:
          heading:
          top:
            subheading:
            text-option-1:
            text-option-2:
            text-option-3:
          bottom:
            subheading: 
            message:
          option-box:
            subject:
            option-1: 
            option-2: 
            option-3:
            option-4: 
          button:
          link:
            description:
          colors:
            background-color:
            textarea-background-color: 
            border-color: 
            heading-color:
            subheading-color:
            text-color:
            button-color: 
            button-text-color:
          fonts:
            heading-font:
            subheading-font:
            text-font: 
            button-font:
_select_data:
  fonts:
      - Cyrene
      - La Obrige
      - Lineal Simples
      - Maglony
      - Mak
      - Misto
      - Brushwell
      - Open Sans, sans-serif
      - Shrikhand, cursive
      - Dream Avenue
      - Amatic SC, cursive
      - Barlow Condensed, sans-serif
      - Belleza, sans-serif
      - Kaushan Script, cursive
      - Montserrat, sans-serif
      - Oooh Baby, cursive
      - Playfair Display, serif
      - Poppins, sans-serif
      - Quicksand, sans-serif
      - Raleway, sans-serif
      - Roboto, sans-serif